extends Node

const ITEMS := {
	"wood": {
		"id": "wood",
		"name": "Wood",
		"max_stack": 99,
		"type": "resource",
		"description": "Basic building material",
		"icon": preload("res://assets/crate.png"),
	},
	"stone": {
		"id": "stone",
		"name": "Stone",
		"max_stack": 99,
		"type": "resource",
		"description": "Hard building material",
		"icon": preload("res://assets/monster_elemental_earth_small.png"),
	},
	"iron_ore": {
		"id": "iron_ore",
		"name": "Iron Ore",
		"max_stack": 99,
		"type": "resource",
		"description": "Raw metal ore",
		"icon": preload("res://assets/monster_elemental_gold_short.png"),
	},
	"fiber": {
		"id": "fiber",
		"name": "Fiber",
		"max_stack": 99,
		"type": "resource",
		"description": "Plant fiber for crafting",
		"icon": preload("res://assets/monster_elemental_plant_small.png"),
	},
	"seed": {
		"id": "seed",
		"name": "Seed",
		"max_stack": 99,
		"type": "resource",
		"description": "A small seed used for farming",
		"icon": preload("res://assets/monster_elemental_plant_small.png"),
	},
	"wheat": {
		"id": "wheat",
		"name": "Wheat",
		"max_stack": 99,
		"type": "resource",
		"description": "A harvested crop used for cooking",
		"icon": preload("res://assets/floor_7.png"),
	},
	"talent_shard": {
		"id": "talent_shard",
		"name": "Talent Shard",
		"max_stack": 99,
		"type": "resource",
		"description": "Used at the Talent Altar",
		"icon": preload("res://assets/monster_elemental_fire_small.png"),
	},
	"wood_sword": {
		"id": "wood_sword",
		"name": "Wood Sword",
		"max_stack": 1,
		"type": "equipment",
		"description": "A basic wooden blade",
		"slot": "weapon",
		"stats": {"attack": 5},
		"durability": 50,
		"max_durability": 50,
		"repair_material": "wood",
		"icon": preload("res://assets/weapon_sword_wooden.png"),
	},
	"wood_shield": {
		"id": "wood_shield",
		"name": "Wood Shield",
		"max_stack": 1,
		"type": "equipment",
		"description": "A simple shield made from bound planks",
		"slot": "offhand",
		"stats": {"defense": 3},
		"durability": 40,
		"max_durability": 40,
		"repair_material": "wood",
		"icon": preload("res://assets/box.png"),
	},
	"stone_pickaxe": {
		"id": "stone_pickaxe",
		"name": "Stone Pickaxe",
		"max_stack": 1,
		"type": "equipment",
		"description": "Useful for rough mining and gathering",
		"slot": "tool",
		"stats": {"gather_speed": 1.5},
		"durability": 60,
		"max_durability": 60,
		"repair_material": "stone",
		"icon": preload("res://assets/weapon_hammer.png"),
	},
	"leather_cap": {
		"id": "leather_cap",
		"name": "Leather Cap",
		"max_stack": 1,
		"type": "equipment",
		"description": "Light head protection made from woven fiber.",
		"slot": "helmet",
		"stats": {"defense": 2},
		"durability": 30,
		"max_durability": 30,
		"repair_material": "fiber",
		"icon": preload("res://assets/monster_orc_armored.png"),
	},
	"leather_vest": {
		"id": "leather_vest",
		"name": "Leather Vest",
		"max_stack": 1,
		"type": "equipment",
		"description": "A flexible vest for dungeon runs.",
		"slot": "chest_armor",
		"stats": {"defense": 4, "max_hp": 10},
		"durability": 40,
		"max_durability": 40,
		"repair_material": "fiber",
		"icon": preload("res://assets/box.png"),
	},
	"iron_sword": {
		"id": "iron_sword",
		"name": "Iron Sword",
		"max_stack": 1,
		"type": "equipment",
		"description": "A sturdier sword for deeper dungeon floors.",
		"slot": "weapon",
		"stats": {"attack": 10},
		"durability": 80,
		"max_durability": 80,
		"repair_material": "iron_ore",
		"icon": preload("res://assets/weapon_sword_steel.png"),
	},
	"bandage": {
		"id": "bandage",
		"name": "Bandage",
		"max_stack": 10,
		"type": "consumable",
		"description": "Wraps wounds and restores health",
		"effect": {"heal": 20},
		"icon": preload("res://assets/flask_green.png"),
	},
	"torch": {
		"id": "torch",
		"name": "Torch",
		"max_stack": 5,
		"type": "consumable",
		"description": "A simple light source for dark spaces",
		"effect": {"light": true},
		"icon": preload("res://assets/torch_1.png"),
	},
	"bread": {
		"id": "bread",
		"name": "Bread",
		"max_stack": 10,
		"type": "consumable",
		"description": "Freshly baked bread that restores health",
		"effect": {"heal": 30},
		"icon": preload("res://assets/floor_5.png"),
	},
	"stew": {
		"id": "stew",
		"name": "Stew",
		"max_stack": 10,
		"type": "consumable",
		"description": "A hearty stew that restores a large chunk of health",
		"effect": {"heal": 50},
		"icon": preload("res://assets/flask_big_red.png"),
	},
}


static func get_item(item_id: String) -> Dictionary:
	if not ITEMS.has(item_id):
		return {}

	return ITEMS[item_id].duplicate(true)
